# Python: Numerical computing with `NumPy`

So far, we've been talking to Python built in data types, classes, and modules, but this is a turning point where we begin to explore the world of numerical programming and data science that enhances Pythons built-in functionality with a series of important packages, namely [NumPy](http://www.numpy.org/), [matplotlib](https://matplotlib.org/), and [pandas](https://pandas.pydata.org/).

Numpy is a library for computational programming. One of the main features is a new type of object, distinct from the built in Python objects we've talked about earlier such as the list. The core of numpy are arrays, specifically multidimensional arrays, which allow you to do all sorts of matrix mathematics extremely efficiently and much, much more.

## Optional Reading
For further reading, please read [Scipy Lecture Notes](https://www.scipy-lectures.org/intro/numpy/operations.html) and [Python Numpy Tutorial](http://cs231n.github.io/python-numpy-tutorial/#numpy) by Justin Johnson at Stanford's Vision Lab. Stanford's Vision Lab is a leader in the field of Computer Vision, and you'll encounter the work of the head of that Lab, Dr. Fei-Fei Li, as you explore the field of machine learning.

## Attribution
*This unit is modified from [SciPy Lecture Notes](http://www.scipy-lectures.org/index.html) under a Creative Commons CC BY 4.0 [license](https://creativecommons.org/licenses/by/4.0/).*

## NumPy is different
The most important thing to remember is that how we use NumPy will vary a little bit from how we use standard Python. It's critical to know both to successfully master Python-based data science, however. We'll walk through a lot of the key functionality, but it's common to mix up standard Python lists and NumPy array techniques as you're learning.

## Importing NumPy

As we discussed previously, there are many packages associated with Python. NumPy is one such package and the convention for importing it is:

In [ ]:
import numpy as np 

As a rule of thumb - place this import statement on the top of your file. You'll likely be using NumPy for most of your code, so always good to have it handy. You can access all of the NumPy functions and modules through dot notation as shown below to create a NumPy array:

In [33]:
import numpy as np         # This is the NumPy import convention using 'np'
a = np.array([0, 1, 2, 3]) # This is how you access a numpy function - this function creates a NumPy array
a

array([0, 1, 2, 3])

## Creating Arrays 
NumPy arrays are memory-efficient containers that provides fast numerical operations. These can be one-dimensional. There are a number of helpful NumPy methods for determining the number of dimensions or the shape of the array:

In [35]:
a = np.array([0, 1, 2, 3]) # Create the array
print(a)

[0 1 2 3]


In [36]:
print(a.ndim) # Get the number of dimensions of the array - for a 1-d array this is 1, for 2-d this is 2, etc.

1


In [37]:
print(a.shape) # Get the shape of the dimensions of the array (since this is a 1-d array, it's a one-element tuple)

(4,)


In [38]:
print(len(a)) # And of course, we can still use some built-in functions here like len

4


For a two dimensional array, we can also explore the array size using the same methods:

In [40]:
b = np.array([[0, 1, 2], [3, 4, 5]])    # 2 x 3 array
print(b)

[[0 1 2]
 [3 4 5]]


In [41]:
print(b.ndim)

2


In [42]:
print(b.shape)

(2, 3)


In [43]:
print(len(b))     # note this returns the size of the first dimension

2


And the same idea continues for 3-d arrays (and onto n-dimensional arrays)

In [44]:
c = np.array([[[1], [2]], [[3], [4]]])  # Here's a three dimensional array
print(c)

[[[1]
  [2]]

 [[3]
  [4]]]


In [45]:
print(c.ndim)

3


In [46]:
print(c.shape)

(2, 2, 1)


In [47]:
print(len(c)) 

2


## Creating sequences of numbers

Most of the time we don't enter data in arrays manually as shown above. We often load data from files, or end up generating data and sequences of numbers using NumPy functions. For example, `arange()` produces a list of values at regular intervals. It's important to note that the range is exclusive of the final value in the list and by default begins at zero (as do all indices in Python).

In [48]:
a = np.arange(10) # Starting at 0, print all values up to (but not including) 10, by a default step size of 1
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [49]:
b = np.arange(1, 9, 2) # Starting at 1, print all values up to (but not including) 9, by a step size of 2
print(b)

[1 3 5 7]


Alternatively, you can specify the number of numbers you'd like to generate linearly spaced between two values and have the `linspace()` function choose a step size for you:

In [50]:
c = np.linspace(0, 1, 6)   # Starting at 0 and ending at 1, generate 6 evenly spaced numbers
print(c)

[ 0.   0.2  0.4  0.6  0.8  1. ]


### Creating custom matrices

There are a number of NumPy function for creating custom matrices to your specifications. For example, you can create an array of all ones (you just need to specify the size of the array you'd like)

In [9]:
a = np.ones((3, 3))  # reminder: (3, 3) is a tuple
print(a)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


Or you can get an array of zeros

In [13]:
b = np.zeros((2, 2))
print(b)

[[ 0.  0.]
 [ 0.  0.]]


An identity matrix which is just a matrix with ones along the diagonal and zeros elsewhere.

In [14]:
c = np.eye(3)
print(c)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


Or a diagonal matrix specifying the values along the diagonal.

In [15]:
d = np.diag(np.array([1, 2, 3, 4]))
print(d)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


## Random number generation

Creating random numbers is useful for many aspect of data analysis and statistical analyses. For this we typically use the NumPy `random` module which has many helpful functions for generating random numbers. 

We can also easily create arrays of random numbers uniformly distributed between 0 and 1 (if this sounds unfamiliar, you'll explore it more in the statistics component of this course)

In [51]:
a = np.random.rand(4)       # uniformly distributed numbers between 0 and 1
print(a)

[ 0.53896468  0.21692611  0.0940325   0.49319938]


In [52]:
a = np.random.rand(4,4)       # uniformly distributed numbers between 0 and 1
print(a)

[[ 0.48845168  0.46477088  0.6817313   0.56911317]
 [ 0.35675968  0.21181415  0.21403554  0.89906183]
 [ 0.85291504  0.96052645  0.14525873  0.47059806]
 [ 0.9737844   0.51138211  0.16393753  0.04320574]]


A very common type of random number is a Gaussian, or normal. You can generate normally distributed random numbers just as easily:

In [53]:
b = np.random.randn(4)      # Gaussian
print(b)

[-0.75826747  0.7269259  -0.49645876  0.11530049]


If we run the above code again, we'll get different values since the numbers are random

In [54]:
b = np.random.randn(4)      # Gaussian
print(b)

[-0.54388415 -0.2329432   1.6788681  -0.19156042]


However, if we want reproducible results, this behavior isn't desirable. We can fix this by setting what's known as a random seed. This generates random numbers, but if the random seed is set (meaning the `np.rand.seed` function is called), the code that follows it will produce the same random numbers each time it is executed. Below we demonstrate this by setting the random seed to a value of 42 (it doesn't matter what the seed is set to, as long as the two pieces of code have the same seed).

In [55]:
np.random.seed(42)        # Setting the random seed
b = np.random.randn(4)      # Gaussian
print(b)

[ 0.49671415 -0.1382643   0.64768854  1.52302986]


In [56]:
np.random.seed(42)        # Setting the random seed
b = np.random.randn(4)      # Gaussian
print(b)

[ 0.49671415 -0.1382643   0.64768854  1.52302986]


## NumPy data types
NumPy arrays have their own data types distinct from the built in Python data types.

You may have noticed that, in some instances, array elements are displayed with a trailing dot (e.g. 2. vs 2). This is due to a difference in the data-type used:

In [18]:
a = np.array([1, 2, 3])
print(a.dtype)

b = np.array([1., 2., 3.])
print(b.dtype)

int32
float64


Different data-types allow us to store data more compactly in memory, but most of the time we simply work with floating point numbers. Note that, in the example above, NumPy auto-detects the data-type from the input.

You can explicitly specify which data-type you want:

In [19]:
c = np.array([1, 2, 3], dtype=float)
print(c.dtype)

float64


And there are other types:

In [20]:
e = np.array([True, False, False, True])
print(e.dtype)

bool


In [24]:
f = np.array(['Bonjour', 'Hello', 'Hallo'])
print(f.dtype)     # <--- strings containing max. 7 letters 

<U7


## Array indexing and slicing with NumPy
The items of an array can be accessed and assigned to the same way as other Python sequences (e.g. lists):

In [28]:
a = np.arange(10)
print(a)
print(a[1])
print((a[0], a[2], a[-1]))

[0 1 2 3 4 5 6 7 8 9]
1
(0, 2, 9)


**Note: Indices begin at 0, like other Python sequences (and C/C++). In contrast, in Fortran or Matlab, indices begin at 1.**

You can reverse a sequence:

In [30]:
print(a[::-1])

[9 8 7 6 5 4 3 2 1 0]


For multidimensional arrays, indexes are tuples of integers:

In [32]:
a = np.diag(np.arange(3))
print(a)
print(a[(1, 1)])
print(a[1,1]) # This is equivalent to the above code

[[0 0 0]
 [0 1 0]
 [0 0 2]]
1
1


In [33]:
a[2, 1] = 10 # third line, second column
print(a)

[[ 0  0  0]
 [ 0  1  0]
 [ 0 10  2]]


In [34]:
print(a[1]) # Return the second row

[0 1 0]


**Note: In 2D, the first dimension corresponds to rows, the second to columns.**

Arrays, like other Python sequences can also be sliced:

In [37]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [38]:
print(a[2:9:3]) # [start:end:step]

[2 5 8]


Note that the last index is not included

In [39]:
a = np.arange(10)
print(a)

a[2:9:3] # [start:end:step]

[0 1 2 3 4 5 6 7 8 9]


array([2, 5, 8])

All three slice components are not required: by default, start is 0, end is the last and step is 1:

In [41]:
print(a[1:3])
print(a[::2])
print(a[3:])

[1 2]
[0 2 4 6 8]
[3 4 5 6 7 8 9]


A small illustrated summary of NumPy indexing and slicing:

<img src="img/numpy_indexing.png">

*Source: Image from [Scipy Lecture Notes](https://www.scipy-lectures.org/intro/numpy/array_object.html)*

You can also combine assignment and slicing

In [42]:
a = np.arange(10)
print(a)
a[5:] = 10
print(a)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 10 10 10 10 10]


In [43]:
b = np.arange(5)
print(b)
a[5:] = b[::-1]
print(a)

[0 1 2 3 4]
[0 1 2 3 4 4 3 2 1 0]


## Copies and views
A slicing operation creates a view on the original array, which is just a way of accessing array data. Thus the original array is not copied in memory. When modifying the view, the original array is modified as well:

In [45]:
a = np.arange(10)
print(a)

b = a[::2]
print(b)

b[0] = 12
print(b)
print(a)  # Careful not to overwrite your original data!

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[12  2  4  6  8]
[12  1  2  3  4  5  6  7  8  9]


You can avoid this overwriting process by creating a copy

In [46]:
a = np.arange(10)
print(a)

c = a[::2].copy()  # force a copy, preventing the original data from being overwritten
print(c)

c[0] = 12
print(c)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[12  2  4  6  8]
[0 1 2 3 4 5 6 7 8 9]


## Fancy indexing
NumPy arrays can be indexed with slices, but also with boolean or integer arrays (**masks**). This method is called **fancy indexing**. It creates **copies not views**.

### Boolean masks
Let's say we wanted to determine all of the values greater than 10 in a set of random integers, and set all of those values to a value of -1.

In [48]:
# Generate the random array of integers
np.random.seed(3) # We set a seed for demonstration purposes so that the random numbers are the same
a = np.random.randint(0, 21, 15)
print(a)

[10  3  8  0 19 10 11  9 10  6  0 20 12  7 14]


Let's create a binary mask that represents whether the number is greater than 10

In [50]:
mask = a > 10
print(mask)

[False False False False  True False  True False False False False  True
  True False  True]


We can use fancy indexing to just look at the values greater than 10. In this case, if the `mask` value is `True`, then the corresponding entry in the array `a` is returned, otherwise, it is not included.

In [51]:
print(a[mask])

[19 11 20 12 14]


This technique can be EXTREMELY helpful for data science computation. Now let's finish this by replacing each of these values with a value of -1

In [52]:
a[mask] = -1
print(a)

[10  3  8  0 -1 10 -1  9 10  6  0 -1 -1  7 -1]


### Indexing with an array of integers
Indexing with integers allows us reference an entry in an array by the integer value (or values) associated with its position in the matrix. We can reference the same index multiple times and in a different order than the original array

In [53]:
# Let's start with a small array
a = np.arange(0, 100, 10)
print(a)

[ 0 10 20 30 40 50 60 70 80 90]


Let's extract the 3rd and 5th entry in the array (remember that indexing starts at 0)

In [54]:
a[[2,4]]

array([20, 40])

We can get much fancier than this, though:

In [55]:
print(a[[2, 3, 2, 4, 2]])

[20 30 20 40 20]


And like the Boolean indexing example, we can assign new values using this technique

In [57]:
a[[9,7]] = -1
print(a)

[ 0 10 20 30 40 50 60 -1 80 -1]


When a new array is created by indexing with an array of integers, the new array has the same shape as the array of integers:

In [58]:
a = np.arange(10) # Original array
print(a)

my_integer_index = np.array([[3, 4],[9, 7]]) # The index we'll use to reference the array values
print(my_integer_index.shape)

print(a[my_integer_index]) # Our new array with integers referenced, in the same shape as the index

[0 1 2 3 4 5 6 7 8 9]
(2, 2)
[[3 4]
 [9 7]]


A small illustrated summary of NumPy fancy indexing for a two-dimensional array:

<img src="img/numpy_fancy_indexing.png">

*Source: Image from [Scipy Lecture Notes](https://www.scipy-lectures.org/intro/numpy/array_object.html)*

## Elementwise array operations
When working with NumPy arrays, you'll often want to perform basic operations on ALL of the elements in a matrix: adding to them, multiplying them by a constant, exponentiating, etc. This is extremely easy with NumPy arrays.

In [62]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [66]:
print(a + 1)

[2 3 4 5]


In [69]:
print(a * 2)

[2 4 6 8]


In [67]:
print(a**2)    # Can raise all terms in an array to a power

[ 1  4  9 16]


In [68]:
print(2**a)    # Can raise a scalar to each of the powers in an array

[ 2  4  8 16]


When working with two NumPy arrays of the same size, standard arithmetic operations are all performed elementwise:

In [73]:
a = np.array([1, 2, 3, 4])
b = np.full(4,2)          # handy function to make an array of all the same value
print(a)
print(b)

[1 2 3 4]
[2 2 2 2]


In [74]:
print(a + b)

[3 4 5 6]


In [75]:
print(a * b)

[2 4 6 8]


In [76]:
print(a / b)

[ 0.5  1.   1.5  2. ]


In [78]:
print(2 ** (a + 1) - b)

[ 2  6 14 30]


## Vectorized code and performance improvements

Vectorized code means working with operations directly on arrays of data rather than looping through the elements of those arrays. Vectorized code in NumPy is many times faster than non-vectorized Python code. 

These operations are much faster than if you did them in pure Python. Note in the speed boost from the example below:

In [8]:
import time

# Using NumPy
a = np.arange(1000000)

start_time = time.time()

a + 1

end_time   = time.time()
print('Elapsed time = {:0.5f} ms'.format(1000 * (end_time - start_time)))

Elapsed time = 1.99628 ms


In [9]:
# Using Python without NumPy
start_time = time.time()

[i+1 for i in a] 

end_time   = time.time()
print('Elapsed time = {:0.5f} ms'.format(1000 * (end_time - start_time)))

Elapsed time = 163.76615 ms


### Vectorized example
Let's say we have an array of 10 million random numbers. We want to compute the sum of squares of that array of data:

$y = \sum_{i=1}^N x_i^2$

How do we go about this? Think about this for yourself for a moment, and try it in Spyder before continuing on.

We'll start by creating an array using the NumPy random.randn module.

In [5]:
import numpy as np
import time

# Generate the random samples - this will be our dataset
np.random.seed(42)
x = np.random.randn(10000000)

Next, we'll compute the sum of the squares first in a for loop. Let's time how long it takes to compute each and report the results and report the output. (We'll compare this time to the vectorized approach next)

*Note: a reminder that all code should be well commented, properly formatted. We'll use the `print()` function to help with that here*

In [15]:
# Compute the sum of squares in non-vectorized way (using a for loop):
t0 = time.time()
sum_of_squares_nonvectorized = 0
for value in x:
    sum_of_squares_nonvectorized += value**2
t1 = time.time()
time_nonvectorized = t1 - t0  

print('Sum of squares = {:0.4f}'.format(sum_of_squares_nonvectorized))
print('Time [sec] (non-vectorized): {:0.4f}'.format(time_nonvectorized))

Sum of squares = 10000271.6721
Time [sec] (non-vectorized): 3.6572


In [16]:
# Compute the sum of squares the vectorized way (using numpy)
t0 = time.time()
sum_of_squares_vectorized = np.sum(x ** 2)
t1 = time.time()
time_vectorized = t1 - t0

print('Sum of squares = {:0.4f}'.format(sum_of_squares_vectorized))
print('Time [sec] (vectorized):     {:0.4f}'.format(time_vectorized))

Sum of squares = 10000271.6721
Time [sec] (vectorized):     0.0469


When we compare the time it takes for each, we can see just how much faster NumPy is!

In [17]:
print('The vectorized code is {:0.1f} times faster than the vectorized code'.format(time_nonvectorized/time_vectorized))

The vectorized code is 78.0 times faster than the vectorized code


## Matrix multiplication

Elementwise multiplication is NOT matrix multiplication. To perform matrix multiplication (which you'll dive deeply into during the linear algebra module), there are a number of methods that can be used, including, most simply, the `@` symbol.

Let's create two matrices to play with:

In [20]:
matrix1 = np.ones((3, 3))
matrix1[1,1] = 2 # Make a small tweak so that it's a more interesting matrix
print(matrix1)

[[ 1.  1.  1.]
 [ 1.  2.  1.]
 [ 1.  1.  1.]]


In [21]:
matrix2 = np.full((3, 3),2)
print(matrix2)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [23]:
print(matrix1 * matrix2)       # Element-wise multiplication

[[ 2.  2.  2.]
 [ 2.  4.  2.]
 [ 2.  2.  2.]]


In [24]:
print(matrix1 @ matrix2)       # Matrix multiplication

[[ 6.  6.  6.]
 [ 8.  8.  8.]
 [ 6.  6.  6.]]


In [25]:
print(matrix1.dot(matrix2))    # Matrix multiplication (another way of doing it)

[[ 6.  6.  6.]
 [ 8.  8.  8.]
 [ 6.  6.  6.]]


In [26]:
print(np.dot(matrix1,matrix2)) # Matrix multiplication (yet another way of doing it)

[[ 6.  6.  6.]
 [ 8.  8.  8.]
 [ 6.  6.  6.]]


Another important matrix operation is the transpose. Let's create a matrix then take its transpose:

In [27]:
x = np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [28]:
print(x.T) # Transpose

[[1 4]
 [2 5]
 [3 6]]


One important distinction is the difference between a 1-dimensional array and higher dimensional arrays. We just showed the transpose of a two dimensional array. If we have a one dimensional array and try to take the transpose, the shape of the array doesn't change since it only has 1 dimension. This is different than what you typically encounter in linear algebra, so it's important to be aware of the difference to avoid errors.

In [29]:
x = np.array([1,2,3])
print(x)
print(x.T)

[1 2 3]
[1 2 3]


You can always see if a NumPy array is 1-D or 2-D by using the `shape` method. Here, we see a 1-element tuple returned.

In [30]:
print(x.shape)
print(x.T.shape)

(3,)
(3,)


Compare this to the case for a 2-d array, where there is a 2-element tuple.

In [32]:
x = np.array([[1,2,3],[4,5,6]])
print(x)
print(x.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


Let's say you wanted the following product: 

\begin{equation*}
\begin{bmatrix}
1 \\
2 \\
3
\end{bmatrix}
\begin{bmatrix}
1 & 2 & 3
\end{bmatrix}
\end{equation*}

For this, one easy approach is to use the outer product function (again, a concept you'll dive more into in linear algebra, but NumPy provides many of the tools you need to work with linear algebra):

In [13]:
print(np.outer(x,x))

[[1 2 3]
 [2 4 6]
 [3 6 9]]


Now, if we tried to do this operation using the `@` symbol for matrix multiplication, we can't because the `x` vector is one dimensional.

In [14]:
print(x.T @ x)
print(x @ x.T)

14
14


However, we can make `x` two dimensional using the `reshape()` method for NumPy arrays.

In [15]:
y = x.reshape((3,1)) # The argument here could also have been (-1,1) where -1 means "infer the value"
print(y)
print(y.shape)

[[1]
 [2]
 [3]]
(3, 1)


Now this reshaped array will allow for an outer product

In [16]:
print(y @ y.T)

[[1 2 3]
 [2 4 6]
 [3 6 9]]


You won't face this often, but this provides some insight into one of the idiosyncrasies of NumPy arrays that you may come up, and hopefully this will help you avoid some of these pitfalls.

## Helpful NumPy functions

NumPy also has many helpful functions for working with arrays to calculate sums, minima, maxima, averages, etc., across the whole array or just specific rows or columns of a matrix. Let's create an array to demonstrate these features.

In [17]:
x = np.array([[0,1],[2,3]])
print(x)

[[0 1]
 [2 3]]


In [247]:
print(np.sum(x))          # Sum of all elements

6


In [248]:
print(np.sum(x, axis=0))  # Sum of each column

[2 4]


In [249]:
print(np.sum(x, axis=1))  # Sum of each row

[1 5]


How sums (and `min`, `max`, `std` standard deviation, etc.) along axes are computed are summarized in this figure:

<img src="img/sum_along_axes.png" width="500">

These same techniques can be used with other NumPy functions that compute various statistics. For example, we can also easily take the `min`, `mean`, or `max`. All of these functions have a `np.<function name>()` version, and many others are a built in method for a data type which you can access by using dot notation:

In [253]:
print(np.max(x, axis=0))

[2 3]


In [252]:
print(x.max(axis=1))     # You can specify the axis to compute along as well (although this is optional)

[1 3]


In [251]:
print(x.min())

0


In [254]:
print(x.mean())

1.5


In [255]:
print(np.std(x))  # Standard deviation

1.11803398875


# Practical Examples

## Example: Counting values
Let's say you have a matrix containing random integers between 0 and 9 as shown below:

In [12]:
import numpy as np

np.random.seed(42)
matrix = np.random.randint(0,10,size=(6, 20))
print(matrix)

[[6 3 7 4 6 9 2 6 7 4 3 7 7 2 5 4 1 7 5 1]
 [4 0 9 5 8 0 9 2 6 3 8 2 4 2 6 4 8 6 1 3]
 [8 1 9 8 9 4 1 3 6 7 2 0 3 1 7 3 1 5 5 9]
 [3 5 1 9 1 9 3 7 6 8 7 4 1 4 7 9 8 8 0 8]
 [6 8 7 0 7 7 2 0 7 2 2 0 4 9 6 9 8 6 8 7]
 [1 0 6 6 7 4 2 7 5 2 0 2 4 2 0 4 9 6 6 8]]


We want to know how many values of each kind are present in each row. For example - how many `1`'s are there, how many `2`'s are there, etc? Therefore if our input row was:
```
[2 1 1 5 9]
```
Then we'd want the output to be an array where each each entry represented how many values there were that equaled the index at that point:
```
Corresponding values: 0 1 2 3 4 5 6 7 8 9
Desired output:      [0 2 1 0 0 1 0 0 0 1]
```
Let's create a function to do that for the above dataset

In [23]:
def counts_values_in_each_row(array):
    # Setup the size of the output array to be the same number of rows, and the number of columns
    #  corresponding to the range of values in the matrix (in this case from 0 to 9)
    maxvalue = np.max(array)
    count    = np.zeros((array.shape[0],maxvalue + 1))
    
    # Here we use the enumerate function which as you recall provides the index as well as values
    for row_index, row_values in enumerate(array):
        (index,row_count) = np.unique(row_values, return_counts=True)
        count[row_index,index] = row_count
    return count

counts_values_in_each_row(matrix)

array([[ 0.,  2.,  2.,  2.,  3.,  2.,  3.,  5.,  0.,  1.],
       [ 2.,  1.,  3.,  2.,  3.,  1.,  3.,  0.,  3.,  2.],
       [ 1.,  4.,  1.,  3.,  1.,  2.,  1.,  2.,  2.,  3.],
       [ 1.,  3.,  0.,  2.,  2.,  1.,  1.,  3.,  4.,  3.],
       [ 3.,  0.,  3.,  0.,  1.,  0.,  3.,  5.,  3.,  2.],
       [ 3.,  1.,  4.,  0.,  3.,  1.,  4.,  2.,  1.,  1.]])

What we've basically implemented here is a very simple histogram. Of course, NumPy has a built-in histogram function that we could have used:

In [22]:
def histogram_values_in_each_row(array):
    # Setup the size of the output array to be the same number of rows, and the number of columns
    #  corresponding to the range of values in the matrix (in this case from 0 to 9)
    maxvalue = np.max(array)
    count    = []
    
    # Here we use the enumerate function which as you recall provides the index as well as values
    for row_index, row_values in enumerate(array):
        # Here we use the histogram function to do our countin for us automatically. Also note
        #   the use of the '_' character to accept the output that np.histogram produces, but that
        #   we won't use
        (row_count, _) = np.histogram(row_values, bins=maxvalue + 1, range=(-0.5,maxvalue + 0.5))
        count.append(row_count.tolist())
    return count

histogram_values_in_each_row(matrix)

[[0, 2, 2, 2, 3, 2, 3, 5, 0, 1],
 [2, 1, 3, 2, 3, 1, 3, 0, 3, 2],
 [1, 4, 1, 3, 1, 2, 1, 2, 2, 3],
 [1, 3, 0, 2, 2, 1, 1, 3, 4, 3],
 [3, 0, 3, 0, 1, 0, 3, 5, 3, 2],
 [3, 1, 4, 0, 3, 1, 4, 2, 1, 1]]

## Example: Replacing values in an array
Imagine you have a dataset and you want to find the two largest values and replace them with the two largest values in another dataset.

In [58]:
import numpy as np

np.random.seed(42)
original    = np.random.randn(10)
replacement = np.random.randint(0,high=60,size=original.shape)

print(original)
print(replacement)

[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337 -0.23413696
  1.57921282  0.76743473 -0.46947439  0.54256004]
[59 20 32 11 57 21 43 24 48 26]


In [59]:
# Let's start by finding the max and the second largest. The max is easy:
maxvalue = original.max()

# Here we use the `where' function
index    = np.where(original==maxvalue)
print(maxvalue)
print(index)

1.57921281551
(array([6], dtype=int64),)


In [60]:
# You'll notive that the `where' function produced an index that is a numpy array inside a tuple 
#  (this is why it's good to look at your data). We can extract it as follows:

# This extracts the numpy array from the tuple 
print(index[0])

# Then the first entry in the array is the index we want
print(index[0][0])

max_index = index[0][0]

[6]
6


In [62]:
# Now we can replace the value of the maximum with the value at the same index in `replacement'
new_array = original.copy()
new_array[max_index] = replacement[max_index]
print(original)
print(new_array)

[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337 -0.23413696
  1.57921282  0.76743473 -0.46947439  0.54256004]
[  0.49671415  -0.1382643    0.64768854   1.52302986  -0.23415337
  -0.23413696  43.           0.76743473  -0.46947439   0.54256004]


Another way we could accomplish this same task is to use **logical indexing**, which is quite helpful here and really gets the job done in two simple lines of code:

In [64]:
new_array = original.copy()

# This will produce an array of all `False' values except for where the maximum is, where it will be `True'
boolean_index_of_max = original == original.max()


new_array[boolean_index_of_max] = replacement[boolean_index_of_max]

print(new_array)

[  0.49671415  -0.1382643    0.64768854   1.52302986  -0.23415337
  -0.23413696  43.           0.76743473  -0.46947439   0.54256004]


Great. But how do we replace the second largest value? Let's follow the lead of our second approach based on logical indexing here - a technique that is used frequently. We'll start by sorting our array to find the second largest value

## Example: Numerical integration

Let's say we want to estimate the integral of the function $f(x)$ on the interval $0\leq x < 2.5$ assuming we only know the following points from $f$:

*Table 1. Dataset containing n=5 observations*

| $x_i$ | 0.0 | 0.5 | 1.0 | 1.5 | 2.0 |
|-|-|-|-|-|-|
| $y_i$ | 6 | 7 | 8 | 4 | 1 |

In [1]:
import numpy as np

x = np.array([0,0.5,1.0,1.5,2.0])
y = np.array([6,7,8,4,1])

# Using a trapezoidal integration approach:
y_dif = (y[:-1] + y[1:]) / 2
dx = x[1:] - x[:-1]

int_y = sum(y_dif * dx )

print('The integral of y is: {:.4}'.format(int_y))

The integral of y is: 11.25


## Next
With NumPy's powerful and efficient computational tools, we can now make beautiful plots using the data analyzed with NumPy using matplotlib.