# Views and Copies Exercises


## Exercise 1

**Close your computer / laptop**. Let's try and work out a few problems in our heads to test our understanding of `numpy` views. Let's start with the following array:

In [1]:
import numpy as np
my_array = np.array([[1, 2, 3], [4, 5, 6]])
print(my_array)

[[1 2 3]
 [4 5 6]]


Now, on a piece of paper write down the value of `my_slice = my_array[:, 1:3]`.

## Exercise 2

Now suppose we run `my_array = my_array * 2`. What does `my_slice` look like?

## Exercise 3

Now suppose we run the code `my_array[:, :] = my_array * 2`. Now what does `my_slice` look like?

## Exercise 4

Stop, open Python, and try running these examples. Were your predictions correct? If not, why not?

## Exercise 5

OK, let's close Python again and go back to pen and paper. Let's also reset `my_array` and start over with the following code:

In [2]:
my_array = np.array([[1, 2, 3], [4, 5, 6]])
print(my_array)

[[1 2 3]
 [4 5 6]]


In [3]:
my_slice = my_array[:, 1:3].copy()
print(my_slice)

[[2 3]
 [5 6]]
