# Folding and Reshaping Matrices

To really understand arrays (be they vectors, matrices, or arrays with more dimensions), it helps to understand how arrays are actually conceptualized in numpy.

In numpy, arrays are thought of as a one-dimensional string of entries + information about how that data should be "folded". The one dimensional vectors we've been working with, in other words, are just one dimensional strings of data + information saying they shouldn't be folded. A matrix is a one dimensional string of data that gets wrapped into rows and columns. That, in fact, is what is stored in `.shape` -- directions on how numpy should think about the data being wrapped.

One consequence of this is that it's very easy to re-fold data in lots of different ways with `numpy`. For example, I can take a 4 x 3 matrix, and make it 3 x 4:

In [12]:
import numpy as np

my_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
my_matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [13]:
my_matrix.reshape((3, 4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

As you can see, numpy thinks of the data as all the numbers along one row (the first dimension) followed by the numbers in the second row, etc., and `reshape` is just changing where each row ends and where the next one begins. 

Indeed, we could even make our data 1 x 12:

In [14]:
my_matrix.reshape((1, 12))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

Numpy isn't limited to changing where each row ends and the next one begins, however; it can also change when one *dimension* ends and where the next one begins. So far we've only explicitly worked with 1 and 2 dimensional arrays, but as we noted before, arrays can organize data along arbitrarily many dimensions. We'll talk about this in detail later, but for the moment, let's just take a look at how we can use `reshape` to make our 2-dimensional matrix a 3-dimensional array (namely a 2 x 2 x 3 array):

In [15]:
my_matrix.reshape((2, 2, 3))

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

So remember: in numpy, an array is always just a string of data that is being folded, and the way the data is folded is indicated by `.shape`, and can always be changed with `.reshape()`.

### Reshape and arange

One place this reshape trick can be very useful is in working with `np.arange()`. Unlike `ones` and `zeros`, to which you can pass the output dimensions you want, `np.arange()` will always return 1 dimensional data. That means that if you want a sequence of numbers in a matrix, you have to combine `np.arange()` with `.reshape()`:

In [16]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
np.arange(20).reshape((4, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### Transpose

OK, one other cool trick that's related to reshape that often comes up when working with `np.arange()`: `.transpose()`. The transpose of a matrix is what you get when you make rows into columns and columns into rows. For example:

In [18]:
my_matrix = np.array([[1, 2, 3], [4, 5, 6]])
my_matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
my_matrix.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

Transpose is often combined with `np.array()` and `.reshape()` because otherwise those two tools will always generate sequences that move across rows, then wrap to the next row:

In [20]:
np.arange(6).reshape((2, 3))

array([[0, 1, 2],
       [3, 4, 5]])

So if you want your sequence to move down your *columns* instead of across your *rows*, you have to transpose your result:

In [21]:
np.arange(6).reshape((2, 3)).transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

Indeed, `.transpose()` is so frequently used in numpy that you can call it with `.T`:

In [22]:
np.arange(6).reshape((2, 3)).T

array([[0, 3],
       [1, 4],
       [2, 5]])

## Exercises 

[to do]