# Matrix Exercises

For the following matrix manipulation exercises, begin by building the following matrix (you'll probably want to just copy-paste this code), which we can imagine is a survey of age, education and income:

In [1]:
import numpy as np

svy = np.array(
    [
        [22_000, 20, 12],
        [65_000, 35, 16],
        [19_000, 55, 11],
        [11_0000, 35, 22],
        [14_000, 21, 12],
        [0, 56, 8],
        [35_000, 42, 12],
    ]
)
svy

array([[ 22000,     20,     12],
       [ 65000,     35,     16],
       [ 19000,     55,     11],
       [110000,     35,     22],
       [ 14000,     21,     12],
       [     0,     56,      8],
       [ 35000,     42,     12]])

## Exercise 1: Summarizing Data

1. What is the average age of all respondents?
2. What is the average income of respondents over 30?
3. What is the average education of respondents with incomes above the average income for all respondents?

## Exercise 2: Editing Data

@Nick: this is going to run into a copy view problem...

The US government is thinking about offering a 10,000 tax credit to anyone making less than 20,000 a year. 

To solve this problem, you'll want to use the `np.hstack` function. As detailed in the [numpy documentation](https://numpy.org/doc/stable/reference/generated/numpy.hstack.html) (seriously, go take a look—numpy documentation is really good and helpful!), `hstack` concatenates ("stacks") arrays horizontally to make new arrays. Just put the arrays you want to concatenate in a list (they must have the same number of rows!) and pass them to `hstack`:


In [2]:
import numpy as np
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array1

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
array2 = np.array([[-10, -11], [-98, -99]])
array2

array([[-10, -11],
       [-98, -99]])

In [5]:
np.hstack([array1, array2])

array([[  1,   2,   3, -10, -11],
       [  4,   5,   6, -98, -99]])

(There's also a function called `np.vstack` to stack matrices or arrays vertically). 

Now use `hstack` to add a new column to the matrix called "after_tax_income" populated with the incomes individuals will get *after* receiving the tax credit if they are eligible. 

Hint: you will want to break this down into several steps.