# ND-Arrays and Broadcasting Exercises

## Exercise 1

**Close Python**. On a piece of paper, write down the final result of the following code:

In [ ]:
import numpy as np
first_matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(first_matrix)

[[1 2 3]
 [4 5 6]]


In [ ]:
second_matrix = np.array([1, 2, 3])
print(second_matrix)

[1 2 3]


```python
first_matrix + second_matrix
```

## Exercise 2

**Keep Python Closed!** Write down the final result of the following code: 

```python
my_vector = np.array([1, 2, 3, 4, 5, 6])
selection = my_vector % 2 == 0
my_vector[selection]
```

## Exercise 3

Now open python and check your answers to Exercises 1 and 2. 