# Working with Vectors

In this reading, we'll introduce you to the most basic form of the numpy array: the vector! We'll start by helping to contextualize and explain why we use vectors, then we'll talk about how to create a vector and use it to do mathematical operations. 

## Vectors in Context

As we mentioned in our last reading, the fundamental workhorse of data science in python in the numpy array. While all numpy arrays are similar, they do come in range of flavors depending on the number of dimensions along which they organize the data they contain:

[Add a well formatted image that looks something like the following here, though with numbers clearly in the boxes:

![numpy array example image](images/numpy_array_flavors.png)

The simplest form of the numpy array is a one-dimensional array, also known as a *vector*. Vectors are a building block of data science because they are often used to represent a collection of different *measurements* or *observations* of the same thing. For example, one may use a vector to hold the heights of everyone in a classroom, or a series of measurements of one's heart rate taken over time.

When we move from one dimension to two, the resulting array is also known as a *matrix*. Matrices (the plural of matrix) are commonly used to represent data in two different ways. 

In the first, we can create a matrix by placing lots of vectors side by side so that each column becomes a different property being measured, and each row becomes a single entity whose properties are being measured. For example, you could imagine storing data about customers in a matrix, where each row is a different individual customer, and each column is a different type of data being collected (days since customer's last purchase, total dollars customer has spent at store, customer age, etc.).

In the second, our matrix may represent fundamentally two-dimensional data, like a picture. A simple black and white image, for example, can be represented by a matrix where the value in each cell is the darkness of the corresponding pixel, and a color image can be created by combining multiple matrices -- one matrix for the amount of blue in each pixel, one for the amount of red, and one for the amount of green. 

While vectors and matrices are probably the most used types of arrays in data science, arrays can be extended into as many dimensions as one wants! For example, we could represent that color image we just described not with three matrices, but with one three-dimensional array composed of the three stacked matrices. Or we might also want to work with a three-dimensional array to represent three-dimensional data, like the results of an MRI scan of a brain with MRI signal strength in each cell, or a climate model with temperatures at a given location and altitude in each cell. Indeed, even higher dimensional arrays are commonly used, even if they're harder to visualize -- for example, if we wanted to model how a three-dimensional climate model changes over time, we could think of that as a series of three-dimensional arrays (each representing the world at a given time) stacked along a fourth dimension (time)!

## Vectors

All the flexibility that makes arrays so powerful can also be **really** overwhelming, so while it's helpful for you to know a little about why arrays are so powerful, we'll start our lesson by just getting a firm grasp on how to work with the simplest form of arrays -- the vector. 

Then, once we feel really comfortable with vectors, we'll talk about how everything you've learned about manipulating vectors can be easily generalized to these higher-dimensional arrays. Because as we'll see, the real magic of arrays isn't that they come in so many flavors -- it's that arrays follow the same logic whether they're simple one-dimensional vectors or 10 dimensional tensors.

### Creating a Vector

Vectors are one-dimensional arrays, which means they have two key properties: first, they organize all their data in a line along one dimension (like the lists you saw in your previous readings), and second they are *homogeneously typed*, meaning each vector only holds data of one type (integer, floating point number, etc.).

The simplest way to create a vector is with the `np.array()` function and a list:

In [28]:
import numpy as np

# A vector of ints
an_integer_vector = np.array([1, 2, 3])
an_integer_vector

array([1, 2, 3])

When you create a vector this way, numpy will do it's best to infer the type of data you want the vector to store based on the data you provided it. You can see what it guessed by checking the `.dtype` attribute of your array:

In [29]:
an_integer_vector.dtype

dtype('int64')

We'll talk more about numpy data types, but for now it's sufficient to know that `int64` is a kind of integer. So in this case, you passed `np.array()` a list of three integers, so it chose to create an array of integers!

Vectors aren't limited to integers, or course -- we can also create vectors of floating point numbers (numbers with decimal components), Booleans, or strings!

In [30]:
# A vector of floats
a_float_vector = np.array([1.7, 2, 3.14])
a_float_vector

array([1.7 , 2.  , 3.14])

In [31]:
a_float_vector.dtype

dtype('float64')

In [32]:
# A vector of booleans
a_boolean_vector = np.array([True, False, True])
a_boolean_vector

a_boolean_vector.dtype

dtype('bool')

In [33]:
# A vector of strings
a_string_vector = np.array(["Red", "Green", "Purple"])
a_string_vector

array(['Red', 'Green', 'Purple'], dtype='<U6')

In [34]:
# Data types for strings look especially strange -- 
# we'll talk about that below!
a_string_vector.dtype

dtype('<U6')

Of course, vectors wouldn't be useful if we had to create a list and pass it to `np.array` anytime we wanted an array, so there are two other primary ways to get arrays. 

First, we can read in data from a file. In reality, this will *probably* be the method you use most for getting data in your career, though we won't really get into reading in data from files till a later lesson.

Second, we can use any one of a number of helper functions designed to generate especially helpful arrays. For example:

In [35]:
# Numbers from 0 to 10
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
# Ones
np.ones(3)

array([1., 1., 1.])

In [37]:
# Zeros
np.zeros(3)

array([0., 0., 0.])

In [38]:
# An array of random values 
# distributed uniformally between 0 and 1
np.random.rand(3)

array([0.38409829, 0.84690088, 0.15466977])

### Numpy Data Types

As we saw above, the way numpy writes out data types looks a little different from what we've previously seen from Python. For example, in Python the number 1 is just an `int`:

In [39]:
type(1)

int

And a floating point number like 3.14 is a `float`:

In [40]:
type(3.14)

float

In numpy, by contrast, we also see these trailing numbers (e.g. `int64` and `float64`). Those trailing numbers just indicate the number of bits (individual 1s and 0s) that numpy is using to store each integer or floating point number. On any modern computer, numpy will default to 64 bits. This is a complexity you really don't need to worry about for now, but basically it's there because you can tell numpy to allocate fewer bits to storing numbers if you want your data to take up less memory *and* you're ok with the trade-offs that come with allocating fewer bits to storing a number (e.g. if you move from `float64` to `float16`, numpy will start ignoring many of the trailing digits of very long numbers).

If at any point you want to control the type of your array (instead of having numpy guess), you can pass an argument to the `dtype` keyword when using `np.array()`. For example, if I want to make sure my array is an array of floats even if the data I'm putting in could be treated as integers, I could type:

In [41]:
as_a_float = np.array([1, 2], dtype="float")
as_a_float

array([1., 2.])

In [42]:
as_a_float.dtype

dtype('float64')

We'll talk more about when you might want to do that in a later reading. 

(Also, note I didn't have to say `float64` -- if you don't give a number when specifying a type, numpy will just use it's own default, which is usually 64.)

## Vector Math

If vectors were just for storing data, they wouldn't be super useful. But one of the best things about vectors is that we can use them to do mathematical operations efficiently.

If you do math with two vectors, one of which has length one, you basically just get the operation applied to every entry.


In [43]:
# Here's what we'll start with
numbers = np.arange(5)
numbers


array([0, 1, 2, 3, 4])

In [44]:
# You can modify all values in a vector 
# by doing math with a vector of length 1
numbers / 10

array([0. , 0.1, 0.2, 0.3, 0.4])

In [45]:
numbers + 10

array([10, 11, 12, 13, 14])

The same thing happens with mathematical functions -- the function gets applied to each entry:

In [46]:
# Modify a vector using a function
np.sqrt(numbers) #square root


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [47]:
np.exp(numbers) #exponentiate

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

If you have two vectors of the same length, mathematical operations will occur "element-wise", meaning the mathematical operation will be applied to the two 1st entries, then the two 2nd entries, then the two 3rd entries, etc. For example, if we were to add our vector of the values 0 through 4 to a vector with two 0s, then two 1s, then a 0 numpy would do the following:

```
0    +     0    =    0  +  0    =    0 
1    +     0    =    1  +  0    =    1 
2    +     1    =    2  +  1    =    3 
3    +     1    =    3  +  1    =    4 
4    +     0    =    4  +  0    =    4 
```

(Obviously, numpy likes to print out vectors sideways, but personally I think of them as column vectors, so have written them out like that here).


In [48]:
# Two vectors with the same number of elements 
numbers2 = np.array([0, 0, 1, 1, 0])
numbers3 = numbers2 + numbers
numbers3


array([0, 1, 3, 4, 4])

## Summarizing vectors 

We often want to get summary statistics from a vector --- that is, learn something general about it by looking beyond its constituent elements. If we have a vector in which each element represents a person's height, for example, we may want to know who the shortest or tallest person is, what the median or mean height is, what the standard deviation is. 

For that, numpy provides a huge range of numeric functions:

In [49]:
np.mean(numbers)

2.0

In [50]:
np.max(numbers)

4

Here's a short (very incomplete!) list of these kinds of functions:

```python
len(numbers) #number of elements 
np.max(numbers) #maximum value
np.min(numbers) #minimum value
np.sum(numbers) #sum of all values in the vector
np.mean(numbers) #mean
np.median(numbers) #median
np.var(numbers) #variance
np.sd(numbers) #standard deviation
np.quantile(numbers) #percentiles in intervals of .25 
```

**Don't** worry about memorizing these or anything -- basically, you just need to have a sense of the kinds of things you can do with functions, and if you ever need one can can't remember the name of the function, you can google it to get the specific function name. 

## Type Promotion

There's one last lesson that's worth learning about vectors, because it can get you in trouble. 

As noted above, vectors can only contain one type of data, but if you try pass a list with different kinds of data to `np.array`, numpy will try and be clever and *find* a way to put all that data in one array by doing something called "Type Promotion." Type promotion is the practice of converting all the data you give it to the same type. For example, if I tried to create a vector by combining a string vector and a numeric vector, numpy would convert the numeric value to a string so all the data could fit in a string vector:


In [51]:
np.array(["Nick", 42])

array(['Nick', '42'], dtype='<U21')

Why did numpy convert `42` to `"42"` and not convert `"Nick"` to a numeric type? Well because `"Nick"` can't be represented as a numeric type in any meaningful sense while any number (like `42`) can always be represented as a character in a meaningful way.

Indeed, there's a hierarchy of data types, where a type lower on the hierarchy can **always** be converted into something higher in the order, but not the other way around. That hierarchy is:

`Boolean` --> `integer` --> `float` --> `string`

When Python is asked to combine data of different types, it will try to move things up this hierarchy by the smallest amount possible in order to make everything the same type.

(Note there are individual cases that can move backwards -- the character `"5"` could logically be turned into `5` -- but you can't always convert a character to a numeric, so for consistently R only moves in directions that are **always** possible. 

For example, if you combine `Boolean` and `float` vectors, Python will convert all of the data into `float` (Remember from our previous reading that Python thinks of `True` as being like `1`, and `False` as being like `0`).


In [52]:
np.array([1, 2.4, True])

array([1. , 2.4, 1. ])

But it **doesn't** convert that data into a `string` vector (even though it could!) because it's trying to make the smallest movements up that hierarchy that it can. 

But if we try to combine `Boolean`, `float`, *and* `string` data, Python would be forced to convert everything into a `string` vector:

In [53]:
np.array([True, 42, "Julio"])

array(['True', '42', 'Julio'], dtype='<U21')

## Recap

- Vectors are collections of data of the same type. 
- Vectors can be created with the `np.array()` function. 
- You can easily do math between any vector and a vector of length 1, or a vector of the same length. 
- You *can* do math between vectors of different lengths that aren't length 1, but... the way it works is weird, so don't. 
- If data of different types are passed to the `np.array()` function, it will type promote them to the lowest type that can store all the input types. 

## Next Steps

Now that we're familiar with vectors, [it's time to learn to manipulate them!](manipulating_vectors.ipynb)