# Doing Math With Vectors

If vectors were just for storing data, they wouldn't be super useful. But one of the best things about vectors is that we can use them to do mathematical operations efficiently.

If you do math with two vectors, one of which has length one, you basically just get the operation applied to every entry.


In [ ]:
import numpy as np

# Here's what we'll start with
numbers = np.arange(5)
numbers


array([0, 1, 2, 3, 4])

In [ ]:
# You can modify all values in a vector 
# by doing math with a vector of length 1
numbers / 10

array([0. , 0.1, 0.2, 0.3, 0.4])

In [ ]:
numbers + 10

array([10, 11, 12, 13, 14])

The same thing happens with mathematical functions -- the function gets applied to each entry:

In [ ]:
# Modify a vector using a function
np.sqrt(numbers) #square root


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [ ]:
np.exp(numbers) #exponentiate

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

If you have two vectors of the same length, mathematical operations will occur "element-wise", meaning the mathematical operation will be applied to the two 1st entries, then the two 2nd entries, then the two 3rd entries, etc. For example, if we were to add our vector of the values 0 through 4 to a vector with two 0s, then two 1s, then a 0 numpy would do the following:

```
0    +     0    =    0  +  0    =    0 
1    +     0    =    1  +  0    =    1 
2    +     1    =    2  +  1    =    3 
3    +     1    =    3  +  1    =    4 
4    +     0    =    4  +  0    =    4 
```

(Obviously, numpy likes to print out vectors sideways, but personally I think of them as column vectors, so have written them out like that here).


In [ ]:
# Two vectors with the same number of elements 
numbers2 = np.array([0, 0, 1, 1, 0])
numbers3 = numbers2 + numbers
numbers3


array([0, 1, 3, 4, 4])

However, note that one can only do this type of element-wise operation with numpy vectors if they are the same length, or you're working with scalar values / vectors of length one. If you try an operation with two vectors of different length, and one *isn't* of size one, you get an error that, for the moment, will feel a little cryptic but which we'll dive into in detail soon:

```python
vect1 = np.array([1, 2, 3])
vect2 = np.array([1, 2, 3, 4, 5, 6])
vect1 + vect2

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/var/folders/tj/s8f2_ks15h315z5thvtnhz8r0000gp/T/ipykernel_30350/1706447136.py in <module>
      1 vect1 = np.array([1, 2, 3])
      2 vect2 = np.array([1, 2, 3, 4, 5, 6])
----> 3 vect1 + vect2

ValueError: operands could not be broadcast together with shapes (3,) (6,) 
```

## Summarizing vectors 

We often want to get summary statistics from a vector --- that is, learn something general about it by looking beyond its constituent elements. If we have a vector in which each element represents a person's height, for example, we may want to know who the shortest or tallest person is, what the median or mean height is, what the standard deviation is. 

For that, numpy provides a huge range of numeric functions:

In [ ]:
np.mean(numbers)

2.0

In [ ]:
np.max(numbers)

4

Here's a short (very incomplete!) list of these kinds of functions:

```python
len(numbers) #number of elements 
np.max(numbers) #maximum value
np.min(numbers) #minimum value
np.sum(numbers) #sum of all values in the vector
np.mean(numbers) #mean
np.median(numbers) #median
np.var(numbers) #variance
np.sd(numbers) #standard deviation
np.quantile(numbers) #percentiles in intervals of .25 
```

**Don't** worry about memorizing these or anything -- basically, you just need to have a sense of the kinds of things you can do with functions, and if you ever need one can can't remember the name of the function, you can google it to get the specific function name. 