# Modifying Subsets of Vectors

The subsetting logic from the previous reading isn't just for extracting subsets of vectors to analyze -- it's also useful for modifying vectors. The idea is that instead of keeping elements that meet a logical condition or occur at a specific index, we can change them. For example, let's consider the vector of the ages we worked with in the last reading. Suppose we mis-entered grandpa's age -- how would we correct that mistake without re-creating the full vector? 

The answer is that we can fix it using indexing, a logical statement, or naming.

In [ ]:
import numpy as np

# Create a vector with ages
age = np.array([50, 55, 80])
age

array([50, 55, 80])

In [ ]:
age[age == 80] = 82 # using a logical statement
age

array([50, 55, 82])

In [ ]:
age[1] = 45         # using indexing
age

array([50, 45, 82])

Note that we can also make modifications to subsets of rows by using subsets on BOTH sides of the assignment operator. 

For example, say we wanted to see how old everyone would be in five years, but Grandpa says we're not allowed to change his age because he's decided he wants to keep saying he's 80 until he dies. Oh, Grandpa.

So what we want to do is take our ages and increase them all by 5. If Grandpa weren't so annoying, we could just do:

```python
ages = ages + 5
```

But Grandpa says we can't increase his age. So we have to (a) pull out the ages that are less than 80, (b) increment them up by 5, and (c) re-insert them, replacing the older age values for people under 80.

In [ ]:
age = np.array([50, 55, 80])

# Get younger ages
younger_ages = age[age < 80]
younger_ages

array([50, 55])

In [ ]:
# Make them all five years older
new_ages = younger_ages + 5
new_ages

array([55, 60])

In [ ]:
# Re-insert
age[age < 80] = new_ages
age

array([55, 60, 80])

Note that this last operation worked because the vector on the left side of the assignment operator had a length of two, and the new vector on the right-hand side was also of length two, so numpy could match the entries being subset on the left to entries on the right one-to-one.

But while we *can* do this is all these separate steps, we can also collapse this:

In [ ]:
age = np.array([50, 55, 80])

In [ ]:
age[age < 80] = age[age < 80] + 5
age

array([55, 60, 80])

Again, note this only worked because we were careful to ensure that the vector on the right of the assignment operator "fit" into the space being subset on the left! This is a trick we use a lot in data science, so make sure you're comfortable with it before proceeding.

## Modifying Vectors and Data Types

You may not have noticed, but up till now we've only being doing "like-for-like" substitutions. For example, when we changed an entry in `age`, we were always replacing one `int` with another.

This is important, because as we discussed in our last reading, vectors are *homogeneously typed*, meaning that unlike lists, you can't put different types of data in an array.

Now when we're *creating* a vector, numpy will use type promotion to pick a type that accommodates everything you're putting into an array. For example, if I pass both bools and integers to `np.array()`, it will just type promote everything to be integers:

In [ ]:
np.array([True, False, 7])

array([1, 0, 7])

But once a vector has been created, numpy stops being so considerate: if you try and cram data of a different type into a vector of a given type, it will try to *coerce* the data into the established type of the array. 

For example, if we try and cram 7 into an array that's already of type `bool`, numpy will *coerce* 7 into type bool (e.g. run `Boolean(7)`), which will turn `7` into `True` *even though this is causing information to be lost*:

In [ ]:
bool_vector = np.array([True, False])
bool_vector

array([ True, False])

In [ ]:
bool_vector[1] = 7
bool_vector

array([ True,  True])

Similarly, if you try and put a floating point number into an integer vector, that float will be type coerced into an integer, which is accomplished by just truncating any information after the decimal:

In [ ]:
int_vector = np.array([1, 2, 3])
int_vector

array([1, 2, 3])

In [ ]:
int_vector[0] = 42.989723798729874
int_vector

array([42,  2,  3])

This is why, as we mentioned in the last reading, you might not always want to let numpy pick your datatypes for you. Suppose in the example above, for example, you know you might later need to put a floating point number into `int_vector` -- you could instead tell numpy to make it a floating point number vector *at creation*:

In [ ]:
no_longer_an_int_vector = np.array([1, 2, 3], dtype="float")
no_longer_an_int_vector[0] = 42.989723798729874
no_longer_an_int_vector

array([42.9897238,  2.       ,  3.       ])

I know this can be a little confusing, so here's a recap:

- When *creating* a vector, numpy will do everything it can to ensure that you don't lose any information by type *promoting* your data to the lowest type that *preserves all the information in your data*. 
- Once a vector has been created, numpy's hands are tied, so it will use type *coercion* to force the data you're trying to put into your existing vector into the established type, *even if that causes information loss.*